### ISSUE TITLE
jsonapi:relation causes Reflect: call of reflect.Value.Elem on struct Value

### ISSUE THREAD

**Issue by 7robertodantas** [google/jsonapi#60]
Hello, I'm new to the Go language and I'm still adapting. I started some tests and had difficulties in making relationships between types using a jsonapi StructTag.

It is giving panic serving to reflect: call to reflect.Value.Elem about struct value

```go


type Post struct {
	Id 		int 	`jsonapi:"primary,posts"`
	Title 		string 	`jsonapi:"attr,title"`
	User		*User	`jsonapi:"relation,user"`
}

type User struct {
	Id 		int 	`jsonapi:"primary,users"`
	Username	string 	`jsonapi:"attr,username"`
	Password	string	`jsonapi:"attr,password"`
}

func handler(w http.ResponseWriter, r *http.Request){
	post := Post{Id: 1, Title: "Title", User: &User{Id:1, Username:"username", Password:"password"}}
	jsonapi.MarshalOnePayload(w, post);
}

func main() {
	http.HandleFunc("/", handler)
	http.ListenAndServe(":8000", nil)
}
```

Is causing this

```
2017/01/12 20:15:48 http: panic serving 127.0.0.1:33616: reflect: call of reflect.Value.Elem on struct Value
goroutine 20 [running]:
net/http.(*conn).serve.func1(0xc420078280)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0x62c2c0, 0xc4200de760)
	/usr/local/go/src/runtime/panic.go:458 +0x243
reflect.Value.Elem(0x649420, 0xc4200de740, 0x99, 0xc4200de740, 0x99, 0x200000003)
	/usr/local/go/src/reflect/value.go:734 +0x114
github.com/google/jsonapi.visitModelNode(0x649420, 0xc4200de740, 0xc420038b50, 0x1, 0xc42007b140, 0x20, 0xc4200de740)
	/home/robertodantas/work/src/github.com/google/jsonapi/response.go:192 +0xc2
github.com/google/jsonapi.MarshalOne(0x649420, 0xc4200de740, 0xc420060000, 0xc420038bb8, 0x410a55)
	/home/robertodantas/work/src/github.com/google/jsonapi/response.go:77 +0x7d
github.com/google/jsonapi.MarshalOnePayload(0x7771c0, 0xc42007da00, 0x649420, 0xc4200de740, 0xc4200de740, 0xc4200a0110)
	/home/robertodantas/work/src/github.com/google/jsonapi/response.go:39 +0x42
main.handler(0x77a8c0, 0xc42007da00, 0xc4200e20f0)
	/home/robertodantas/work/src/github.com/7robertodantas/api/api.go:22 +0x185
net/http.HandlerFunc.ServeHTTP(0x696898, 0x77a8c0, 0xc42007da00, 0xc4200e20f0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0x794ee0, 0x77a8c0, 0xc42007da00, 0xc4200e20f0)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc420078200, 0x77a8c0, 0xc42007da00, 0xc4200e20f0)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420078280, 0x77ae00, 0xc4200743c0)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

Could someone help me and tell me what I'm doing wrong?

**Comment by aren55555** [comment]
You ultimately need to provide MarshalOnePayload with a ptr. So that leaves you able to do either:

```go
jsonapi.MarshalOnePayload(w, &post)
```

or:

```go
post := &Post{...}
```
